import type { Profile, HabitWithCompletions, JournalEntry, FocusSession } from '@/types';
import type { Sprint, MIT, HygieneConfig, HygieneLog } from '@/types/summis';

const now = new Date();
const daysAgo = (d: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - d);
  return date.toISOString();
};

const dateStr = (d: number) => {
  const date = new Date(now);
  date.setDate(date.getDate() - d);
  return date.toISOString().split('T')[0];
};

const demoTier = (process.env.EXPO_PUBLIC_DEMO_TIER === 'free' ? 'free' : 'pro') as Profile['subscription_tier'];

// ── Legacy mock data (kept for backward compatibility) ────────────────

export const MOCK_PROFILE: Profile = {
  id: 'demo-user-001',
  display_name: 'Alex',
  timezone: Intl.DateTimeFormat().resolvedOptions().timeZone,
  onboarding_completed: true,
  user_goal: 'focus',
  wake_time: '07:00',
  chronotype: 'bi_phasic',
  subscription_tier: demoTier,
  created_at: daysAgo(30),
  sprint_duration_preference: 45,
  peak_window_start: '09:00',
  peak_window_end: '12:00',
  afternoon_window_start: '14:00',
  afternoon_window_end: '16:00',
  daily_sprint_target: 3,
  phone_placement_commitment: 'other_room',
  notification_audit_completed: true,
  hygiene_setup_completed: true,
};

export const MOCK_HABITS: HabitWithCompletions[] = [];

export const MOCK_JOURNAL_ENTRIES: JournalEntry[] = [];

export const MOCK_FOCUS_SESSIONS: FocusSession[] = [];

// ── Summis mock data ─────────────────────────────────────────────────

export const MOCK_HYGIENE_CONFIGS: HygieneConfig[] = [
  {
    id: 'hc-1',
    user_id: 'demo-user-001',
    practice: 'phone_away',
    label: 'Phone in Another Room',
    description: 'Ward et al. (2017): Even a silent, face-down phone reduces working memory capacity.',
    is_active: true,
    created_at: daysAgo(30),
  },
  {
    id: 'hc-2',
    user_id: 'demo-user-001',
    practice: 'notifications_off',
    label: 'Non-Essential Notifications Off',
    description: 'Each notification pulls attention even if not acted on.',
    is_active: true,
    created_at: daysAgo(30),
  },
  {
    id: 'hc-3',
    user_id: 'demo-user-001',
    practice: 'dnd_active',
    label: 'Do Not Disturb Enabled',
    description: 'Eliminating the possibility of interruption reduces cognitive vigilance overhead.',
    is_active: true,
    created_at: daysAgo(30),
  },
];

export const MOCK_HYGIENE_LOGS: HygieneLog[] = [
  // Today's logs
  {
    id: 'hl-1',
    user_id: 'demo-user-001',
    practice: 'phone_away',
    date: dateStr(0),
    compliant: true,
    sprint_id: null,
    logged_at: daysAgo(0),
  },
  {
    id: 'hl-2',
    user_id: 'demo-user-001',
    practice: 'notifications_off',
    date: dateStr(0),
    compliant: true,
    sprint_id: null,
    logged_at: daysAgo(0),
  },
  {
    id: 'hl-3',
    user_id: 'demo-user-001',
    practice: 'dnd_active',
    date: dateStr(0),
    compliant: false,
    sprint_id: null,
    logged_at: daysAgo(0),
  },
  // Yesterday's logs
  {
    id: 'hl-4',
    user_id: 'demo-user-001',
    practice: 'phone_away',
    date: dateStr(1),
    compliant: true,
    sprint_id: 'sprint-1',
    logged_at: daysAgo(1),
  },
  {
    id: 'hl-5',
    user_id: 'demo-user-001',
    practice: 'notifications_off',
    date: dateStr(1),
    compliant: true,
    sprint_id: 'sprint-1',
    logged_at: daysAgo(1),
  },
  {
    id: 'hl-6',
    user_id: 'demo-user-001',
    practice: 'dnd_active',
    date: dateStr(1),
    compliant: true,
    sprint_id: 'sprint-1',
    logged_at: daysAgo(1),
  },
  // 2 days ago
  {
    id: 'hl-7',
    user_id: 'demo-user-001',
    practice: 'phone_away',
    date: dateStr(2),
    compliant: true,
    sprint_id: 'sprint-2',
    logged_at: daysAgo(2),
  },
  {
    id: 'hl-8',
    user_id: 'demo-user-001',
    practice: 'notifications_off',
    date: dateStr(2),
    compliant: false,
    sprint_id: 'sprint-2',
    logged_at: daysAgo(2),
  },
  {
    id: 'hl-9',
    user_id: 'demo-user-001',
    practice: 'dnd_active',
    date: dateStr(2),
    compliant: true,
    sprint_id: 'sprint-2',
    logged_at: daysAgo(2),
  },
];

export const MOCK_MITS: MIT[] = [
  {
    id: 'mit-1',
    user_id: 'demo-user-001',
    date: dateStr(0),
    title: 'Draft Q2 project proposal',
    estimated_minutes: 45,
    actual_minutes: null,
    completed: false,
    completed_at: null,
    sort_order: 1,
    sprint_id: null,
    created_at: daysAgo(0),
  },
  {
    id: 'mit-2',
    user_id: 'demo-user-001',
    date: dateStr(0),
    title: 'Review team design documents',
    estimated_minutes: 30,
    actual_minutes: null,
    completed: false,
    completed_at: null,
    sort_order: 2,
    sprint_id: null,
    created_at: daysAgo(0),
  },
  {
    id: 'mit-3',
    user_id: 'demo-user-001',
    date: dateStr(0),
    title: 'Reply to client emails',
    estimated_minutes: 20,
    actual_minutes: null,
    completed: false,
    completed_at: null,
    sort_order: 3,
    sprint_id: null,
    created_at: daysAgo(0),
  },
  // Yesterday's MITs
  {
    id: 'mit-4',
    user_id: 'demo-user-001',
    date: dateStr(1),
    title: 'Write project brief for client presentation',
    estimated_minutes: 60,
    actual_minutes: 62,
    completed: true,
    completed_at: daysAgo(1),
    sort_order: 1,
    sprint_id: 'sprint-1',
    created_at: daysAgo(1),
  },
  {
    id: 'mit-5',
    user_id: 'demo-user-001',
    date: dateStr(1),
    title: 'Research competitor pricing models',
    estimated_minutes: 45,
    actual_minutes: 38,
    completed: true,
    completed_at: daysAgo(1),
    sort_order: 2,
    sprint_id: 'sprint-2',
    created_at: daysAgo(1),
  },
];

export const MOCK_SPRINTS: Sprint[] = [
  {
    id: 'sprint-1',
    user_id: 'demo-user-001',
    date: dateStr(1),
    intention: 'Write project brief for client presentation',
    duration_minutes: 45,
    phase: 'reflection',
    started_at: new Date(now.getTime() - 86400000 - 3600000).toISOString(),
    ended_at: new Date(now.getTime() - 86400000 - 1800000).toISOString(),
    completed: true,
    phone_away: true,
    dnd_enabled: true,
    environment_ready: true,
    focus_quality: 4,
    intention_met: 'yes',
    reflection_note: 'Good flow state in the second half. Finished brief 2 minutes early.',
    interruptions: 1,
    interruption_types: ['Thought'],
    mit_id: 'mit-4',
  },
  {
    id: 'sprint-2',
    user_id: 'demo-user-001',
    date: dateStr(1),
    intention: 'Research competitor pricing models',
    duration_minutes: 30,
    phase: 'reflection',
    started_at: new Date(now.getTime() - 86400000 - 1800000).toISOString(),
    ended_at: new Date(now.getTime() - 86400000).toISOString(),
    completed: true,
    phone_away: true,
    dnd_enabled: false,
    environment_ready: true,
    focus_quality: 3,
    intention_met: 'partially',
    reflection_note: null,
    interruptions: 2,
    interruption_types: ['Phone', 'Person'],
    mit_id: 'mit-5',
  },
  {
    id: 'sprint-3',
    user_id: 'demo-user-001',
    date: dateStr(2),
    intention: 'Review architecture proposal for new feature',
    duration_minutes: 50,
    phase: 'reflection',
    started_at: new Date(now.getTime() - 172800000 - 3600000).toISOString(),
    ended_at: new Date(now.getTime() - 172800000 - 600000).toISOString(),
    completed: true,
    phone_away: true,
    dnd_enabled: true,
    environment_ready: true,
    focus_quality: 5,
    intention_met: 'yes',
    reflection_note: 'Excellent clarity. All three practices in place made a huge difference.',
    interruptions: 0,
    interruption_types: [],
    mit_id: null,
  },
  {
    id: 'sprint-4',
    user_id: 'demo-user-001',
    date: dateStr(3),
    intention: 'Draft presentation slides for team meeting',
    duration_minutes: 45,
    phase: 'reflection',
    started_at: new Date(now.getTime() - 259200000 - 2700000).toISOString(),
    ended_at: new Date(now.getTime() - 259200000).toISOString(),
    completed: true,
    phone_away: false,
    dnd_enabled: true,
    environment_ready: true,
    focus_quality: 3,
    intention_met: 'partially',
    reflection_note: 'Phone accessibility hurt focus. Noticed 2 distraction checks.',
    interruptions: 3,
    interruption_types: ['Phone', 'Phone', 'Thought'],
    mit_id: null,
  },
  {
    id: 'sprint-5',
    user_id: 'demo-user-001',
    date: dateStr(4),
    intention: 'Code review + feedback for junior dev',
    duration_minutes: 40,
    phase: 'reflection',
    started_at: new Date(now.getTime() - 345600000 - 2400000).toISOString(),
    ended_at: new Date(now.getTime() - 345600000).toISOString(),
    completed: true,
    phone_away: true,
    dnd_enabled: true,
    environment_ready: false,
    focus_quality: 4,
    intention_met: 'yes',
    reflection_note: null,
    interruptions: 1,
    interruption_types: ['Person'],
    mit_id: null,
  },
  {
    id: 'sprint-6',
    user_id: 'demo-user-001',
    date: dateStr(5),
    intention: 'Strategic planning session prep',
    duration_minutes: 60,
    phase: 'reflection',
    started_at: new Date(now.getTime() - 432000000 - 3600000).toISOString(),
    ended_at: new Date(now.getTime() - 432000000).toISOString(),
    completed: true,
    phone_away: true,
    dnd_enabled: true,
    environment_ready: true,
    focus_quality: 5,
    intention_met: 'yes',
    reflection_note: 'All practices active. Deepest focus state this week.',
    interruptions: 0,
    interruption_types: [],
    mit_id: null,
  },
];
